/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/fixed/work-space.glb --types --typescript 
Author: karimijannes0 (https://sketchfab.com/karimijannes0)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/modern-marble-work-desk-with-white-apple-theme-c3fb1f89ecc44647ac8b0923fb7dd849
Title: Modern Marble Work Desk With White Apple Theme
*/

'use client';

import { useGLTF, useVideoTexture } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFAction = {
  name: string;
  action: THREE.AnimationAction;
};

type GLTFResult = GLTF & {
  nodes: {
    Object_11_Metal001_0: THREE.Mesh;
    Object_13_Metal2001_0: THREE.Mesh;
    Object_16_LightBlue001_0: THREE.Mesh;
    Object_16001_screen_0: THREE.Mesh;
    Object_16002_screen_0: THREE.Mesh;
    Object_18_txmOgsLZbdKJcEU_0: THREE.Mesh;
    Object_22001_White001_0: THREE.Mesh;
    Object_26_Chrome001_0: THREE.Mesh;
    Object_28_CamBlack001_0: THREE.Mesh;
    Object_30_Lens001_0: THREE.Mesh;
    Object_32_Glass001_0: THREE.Mesh;
    Object_34_Black002_0: THREE.Mesh;
    Object_36_Yellow001_0: THREE.Mesh;
    Object_8_txmOgsLZbdKJcEU_0: THREE.Mesh;
    Modern_Office_Desk_Marble_0: THREE.Mesh;
    Object_4_carbon_0: THREE.Mesh;
    Object_5_carbon_0: THREE.Mesh;
    aiHhzEmqAnKWvuZ_EFVjrvWSJmAgjPd_0: THREE.Mesh;
    bGQMFmxTXZZEOSB_sIvkPEZgWXyskPl_0: THREE.Mesh;
    BhmwvFLjAMopdsz_UhciuwjbkbbeuzB_0: THREE.Mesh;
    COalyZNmKBMRDJA_RWIxOmVjlQCyowf_0: THREE.Mesh;
    cTxlpXifIUtmOwe_CUqnbzGvHvsjfjx_0: THREE.Mesh;
    dIGFCvApVXVovwW_UFhCTmjKLQhiPGC_0: THREE.Mesh;
    DucfrfCAqHqPEBB_DEAWTVXLuSZtcDP_0: THREE.Mesh;
    eaMMaIHSUtZTmwM_rXOHcxkhnKbZRNb_0: THREE.Mesh;
    eJrZgbUbLcjUmXb_HRWfsqTNPFmjalx_0: THREE.Mesh;
    EjxsCCuCosYwuek_IvcPCDoDmyBTWLH_0: THREE.Mesh;
    elzKjZVZogRbidI_uQtVjGIzYkvkoNE_0: THREE.Mesh;
    gMjIpJkwdihsuve_QWnVWluKdJslXlp_0: THREE.Mesh;
    grgDQRSnIrRfYHl_qJYXGHykgiNTzst_0: THREE.Mesh;
    hbRQuyafLOAJHbc_IMKGQaLyUgfVxBg_0: THREE.Mesh;
    hmCcMVIPuALtvnB_NizfUyGpiAoDFWH_0: THREE.Mesh;
    IvQyRpNNnwrbsxL_sIvkPEZgWXyskPl_0: THREE.Mesh;
    jdDNrasBlJHUmOI_RWIxOmVjlQCyowf_0: THREE.Mesh;
    jfcwgJrUYqWmTbS_kMVeqkDlEeNLAmH_0: THREE.Mesh;
    LBPtZdGyIpXPukr_yifgXaDcdXXvJAt_0: THREE.Mesh;
    LLOlBTHSUCLvvWd_DEAWTVXLuSZtcDP_0: THREE.Mesh;
    MgIBLXqrHqrffJA_UhciuwjbkbbeuzB_0: THREE.Mesh;
    MNJNItsqFHPCYBO_RWIxOmVjlQCyowf_0: THREE.Mesh;
    ogZjMUJrEEmipKZ_nsOjGvnekvGXrhm_0: THREE.Mesh;
    pDHQtpoBgcNkYgT_pJGidJSmpkqoZJU_0: THREE.Mesh;
    PwgdzFHtyijxfkM_pueCqTeVMmaUmSr_0: THREE.Mesh;
    pwunQleuznjoKDo_zSrAlRDhvfAhSPV_0: THREE.Mesh;
    PZkUDTueaTlRUIB_RWIxOmVjlQCyowf_0: THREE.Mesh;
    QQjtoFlaLxDYFcf_nxZSRGOrkZuiBOL_0: THREE.Mesh;
    QWynJfbYSasNZHl_rXOHcxkhnKbZRNb_0: THREE.Mesh;
    rZZGdJgeDlvDaPX_UFhCTmjKLQhiPGC_0: THREE.Mesh;
    SbeMRorWoNyXlAe_ZchRNZkxDgmgJXH_0: THREE.Mesh;
    SDFncRVROIaGmdP_Material006_0: THREE.Mesh;
    SDXaYLHOunwCLHZ_CUqnbzGvHvsjfjx_0: THREE.Mesh;
    ssmfkcRvklZSIzZ_EFVjrvWSJmAgjPd_0: THREE.Mesh;
    tIqFBnXlPHHchZM_CUqnbzGvHvsjfjx_0: THREE.Mesh;
    UOKfQrXTIiZEYIa_pueCqTeVMmaUmSr_0: THREE.Mesh;
    VeBGZTrfnhHdOwL_CUqnbzGvHvsjfjx_0: THREE.Mesh;
    veExVWBHjiIlgtN_WaTFoANPRxreBrE_0: THREE.Mesh;
    vERhpGKnTDAqPYM_OqztnpgkHPpVRLf_0: THREE.Mesh;
    VkZCcwdEWjLPPEB_RWIxOmVjlQCyowf_0: THREE.Mesh;
    vUnJNCoGwAVQHLJ_EFVjrvWSJmAgjPd_0: THREE.Mesh;
    vurcCjJgfXlGxGa_sIvkPEZgWXyskPl_0: THREE.Mesh;
    WZNlAtpdtvoXdBP_UhciuwjbkbbeuzB_0: THREE.Mesh;
    XqkMoScNZNSWfSO_pueCqTeVMmaUmSr_0: THREE.Mesh;
    yyGZPAZQuGPMcxX_sIvkPEZgWXyskPl_0: THREE.Mesh;
    zXWNaEcOhoAIySc_JbkUHwfUMhKPsVU_0: THREE.Mesh;
    Object_10_Cam_Glass_0: THREE.Mesh;
    Object_11001_Cam_lens_0: THREE.Mesh;
    Object_13001_Flash_0: THREE.Mesh;
    Object_14_Flash_Glass_0: THREE.Mesh;
    Object_15_Gray_0: THREE.Mesh;
    Object_2_Antenna_Plastic_0: THREE.Mesh;
    Object_20_Rearcase_hole_0: THREE.Mesh;
    Object_21_SAMSUNG_LOGO_0: THREE.Mesh;
    Object_22_Sensor_0: THREE.Mesh;
    Object_23_SpeakerMic_0: THREE.Mesh;
    Object_24_Usb_1_0: THREE.Mesh;
    Object_25_Usb_2_0: THREE.Mesh;
    Object_26001_Zoom_Cam_0: THREE.Mesh;
    Object_27_Rearcase_0: THREE.Mesh;
    Object_17_Pen_Body_0: THREE.Mesh;
    Object_18001_Pen_Button_0: THREE.Mesh;
    Object_19_Pen_Top_0: THREE.Mesh;
    Object_28001_Rearcase_0: THREE.Mesh;
    Object_29_material_0: THREE.Mesh;
    Object_3_BackCamDeco_0: THREE.Mesh;
    Object_4001_BackCover_Glass_hole_0: THREE.Mesh;
    Object_5001_Back_Cover_Glass_0: THREE.Mesh;
    Object_6_Bezel_0: THREE.Mesh;
    Object_7_Black_hole_0: THREE.Mesh;
    Object_8001_Cam_Bezel_0: THREE.Mesh;
    Object_9_Cam_Body_0: THREE.Mesh;
    Object_12_samsung_display_0: THREE.Mesh;
    defaultMaterial001_Material001_0: THREE.Mesh;
    defaultMaterial002_Material001_0: THREE.Mesh;
    defaultMaterial003_Material002_0: THREE.Mesh;
    Apple_0_Material_0: THREE.Mesh;
    Apple_0_Material002_0: THREE.Mesh;
    AJbdxpwuEnTzrzs_AAwwZzgtkuPlzHG_0: THREE.Mesh;
    AMHLoKClaWHHFTd_txmOgsLZbdKJcEU_0: THREE.Mesh;
    DDRlrgtqbHRuMFK_lLHxDzeGesTXsDV_0: THREE.Mesh;
    dJHERinFsWDVoRO_jBmFawgSnuFgwvz_0: THREE.Mesh;
    DyNEUHcqFmykLnq_inVgKrsjPCHlidG_0: THREE.Mesh;
    epNEVLwjxulvcVT_lqsMNfAMfMMYNWh_0: THREE.Mesh;
    EvwofeNdSOiKwJA_ZxCcWNVXIHaKOMZ_0: THREE.Mesh;
    fdelRQvrAPluxYI_DlUleWLCfHhnvHH_0: THREE.Mesh;
    fiEriZEEzWBKpIW_kiplkEfHPICMwOL_0: THREE.Mesh;
    FPkLYEUKWIzIvRB_mnvREVAVeWlYOOT_0: THREE.Mesh;
    gCWqWSEWWHMcDGU_LDkudPLsuhAeDOm_0: THREE.Mesh;
    gstnwkkYxUMfexU_xhFoqVSMOeACiXV_0: THREE.Mesh;
    ibtGhYAKvcwGziZ_rrvhCJMaYTHrDoz_0: THREE.Mesh;
    idZbmiqfxcsskPw_wYuvWRhcBAnXIkk_0: THREE.Mesh;
    jANFYvUCGDdkwwM_ShHQJgcVqRHxvCB_0: THREE.Mesh;
    JYlWWVpXsttJXNT_fLPLjcBAOBBZMBG_0: THREE.Mesh;
    kgVGkcNjSqcogpi_zMLlCcSBPIDbYDP_0: THREE.Mesh;
    KvIMyWFPpFISdov_lrBjRRoUCQJnnrw_0: THREE.Mesh;
    KwHYbQNqIDhjHSe_txmOgsLZbdKJcEU_0: THREE.Mesh;
    MEVcNNvcPYMgxhw_axGqhJIfzrbRmtI_0: THREE.Mesh;
    mJlqEXxPCKLwQZq_HmbIobmriOJHOjV_0: THREE.Mesh;
    NoxSUxuQtcYfBlX_MEIyWDLxyHySdQS_0: THREE.Mesh;
    NZWwoBiiqXPyUvr_JUvPVJgNgUOAMPH_0: THREE.Mesh;
    ohJAMQPFJETFsDW_NebQvzRLlLTGfUN_0: THREE.Mesh;
    PGROoHXqRGLyzpv_jBmFawgSnuFgwvz_0: THREE.Mesh;
    pHQfWFRRACikJLz_JUvPVJgNgUOAMPH_0: THREE.Mesh;
    PuPREzUbjRnwByi_DOGSvSvaIOKOGEB_0: THREE.Mesh;
    QxirwGJHRdjmSQM_sTZzuJicxcBhqMT_0: THREE.Mesh;
    rrgnrcJtagJiaPm_JUvPVJgNgUOAMPH_0: THREE.Mesh;
    sbMQfpLUHxjxYbY_bHMusfkozOIvqtp_0: THREE.Mesh;
    SDBahcjiXkZtYxZ_FLgLVPAjfWzuEtb_0: THREE.Mesh;
    SgUfbhhareNQkuj_xhFoqVSMOeACiXV_0: THREE.Mesh;
    sqpzxMMcSNEzeaN_KYAZVdlNwZfXbEf_0: THREE.Mesh;
    UcDFxvKUvTmdLHf_txmOgsLZbdKJcEU_0: THREE.Mesh;
    vVWnLQQWauJmoea_BhzUwdkPybcVRaA_0: THREE.Mesh;
    WggVFGrkJUBSkuH_txmOgsLZbdKJcEU_0: THREE.Mesh;
    WHTbdsLSupTMovb_ZxCcWNVXIHaKOMZ_0: THREE.Mesh;
    xVttQMiYmYuArAD_kiplkEfHPICMwOL_0: THREE.Mesh;
    YAznSNOjLfkryuQ_bEezaHeEnrDoiaK_0: THREE.Mesh;
    ysyLqNtrPcvbRdQ_QlBwJAiKCnKYdcl_0: THREE.Mesh;
    zmxolQOwzgtuHGo_ynLkpcwlGVMwvHR_0: THREE.Mesh;
    ZrGEEtRvTICtxtV_UvbMHfZlJbAYJww_0: THREE.Mesh;
    RMOxPfNmwvXDNGs_txmOgsLZbdKJcEU_0: THREE.Mesh;
    Plane002__0: THREE.Mesh;
    Cylinder055_Glass002_0: THREE.Mesh;
    Cylinder044_Material003_0: THREE.Mesh;
    Cylinder043_Material003_0: THREE.Mesh;
    Cylinder056__0: THREE.Mesh;
    Cylinder047_Material015_0: THREE.Mesh;
    Cylinder042_Material003_0: THREE.Mesh;
    Cube073_Wood_0: THREE.Mesh;
    Cube072_Wood_0: THREE.Mesh;
    Cube071_Wood_0: THREE.Mesh;
    Desk_lamp_Wood_0: THREE.Mesh;
    Object_10001_Material004_0: THREE.Mesh;
    Object_9001_Material005_0: THREE.Mesh;
    Object_14001_Material005_0: THREE.Mesh;
    Object_4002_emission_0: THREE.Mesh;
    Object_5002_Material005_0: THREE.Mesh;
    Object_12001_glass_0: THREE.Mesh;
    Object_7001_alarm_sign_0: THREE.Mesh;
    Object_16003_Material010_0: THREE.Mesh;
    Object_18002_knob_0: THREE.Mesh;
    Object_19001_knob_2_0: THREE.Mesh;
    Object_10002_Rubber_0: THREE.Mesh;
    Object_11002_Rubber_0: THREE.Mesh;
    Object_12002_Rubber_0: THREE.Mesh;
    Object_13002_Rubber_0: THREE.Mesh;
    Object_14002_txmOgsLZbdKJcEU_0: THREE.Mesh;
    Object_15001_Rubber_0: THREE.Mesh;
    Object_16004_Rubber_0: THREE.Mesh;
    Object_17001_Rubber_0: THREE.Mesh;
    Object_18003_SILVER_0: THREE.Mesh;
    Object_19002_Material007_0: THREE.Mesh;
    Object_2001_Copper_0: THREE.Mesh;
    Object_20001_txmOgsLZbdKJcEU_0: THREE.Mesh;
    Object_21001_black_032half_032matte_0: THREE.Mesh;
    Object_22002_txmOgsLZbdKJcEU_0: THREE.Mesh;
    Object_3001_Grill_0: THREE.Mesh;
    Object_4003_Led_032Emitter_0: THREE.Mesh;
    Object_5003_Led_Cover_0: THREE.Mesh;
    Object_6001_Smooth_032Rubber_0: THREE.Mesh;
    Object_7002_White_032Reflector_0: THREE.Mesh;
    Object_8002_label_0: THREE.Mesh;
    Object_9002_Rubber_0: THREE.Mesh;
    Object_15002_sofa_1M_0: THREE.Mesh;
    Plane060_paper001_0: THREE.Mesh;
    Plane060_paper001_0_1: THREE.Mesh;
    Plane060_paper001_0_2: THREE.Mesh;
    Plane060_paper001_0_3: THREE.Mesh;
    Plane060_paper001_0_4: THREE.Mesh;
    Plane060_paper001_0_5: THREE.Mesh;
    Plane060_couro_2k_0: THREE.Mesh;
    Plane060_Material009_0: THREE.Mesh;
    Cylinder001_Metal_preto001_0: THREE.Mesh;
    Cylinder001_Metal_cromado_0: THREE.Mesh;
    Circle_Metal_ouro_0: THREE.Mesh;
    Object_4004_Sheets_0: THREE.Mesh;
    Object_4004_Sheets_0_1: THREE.Mesh;
    Object_4004_Sheets_0_2: THREE.Mesh;
    Object_5004_Sheets_0: THREE.Mesh;
    Object_6005_Cover_0: THREE.Mesh;
    Object_7004_Binding_0: THREE.Mesh;
  };
  materials: {
    ['Metal.001']: THREE.MeshStandardMaterial;
    ['Metal2.001']: THREE.MeshStandardMaterial;
    ['LightBlue.001']: THREE.MeshStandardMaterial;
    RWIxOmVjlQCyowf: THREE.MeshStandardMaterial;
    txmOgsLZbdKJcEU: THREE.MeshStandardMaterial;
    Merged_materials: THREE.MeshStandardMaterial;
    ['Chrome.001']: THREE.MeshStandardMaterial;
    ['Black.002']: THREE.MeshStandardMaterial;
    Marble: THREE.MeshStandardMaterial;
    carbon: THREE.MeshStandardMaterial;
    EFVjrvWSJmAgjPd: THREE.MeshStandardMaterial;
    sIvkPEZgWXyskPl: THREE.MeshStandardMaterial;
    UhciuwjbkbbeuzB: THREE.MeshStandardMaterial;
    RWIxOmVjlQCyowf_0: THREE.MeshStandardMaterial;
    UFhCTmjKLQhiPGC: THREE.MeshStandardMaterial;
    HRWfsqTNPFmjalx: THREE.MeshStandardMaterial;
    rXOHcxkhnKbZRNb: THREE.MeshStandardMaterial;
    IvcPCDoDmyBTWLH: THREE.MeshStandardMaterial;
    SpeakerMic: THREE.MeshStandardMaterial;
    QWnVWluKdJslXlp: THREE.MeshStandardMaterial;
    qJYXGHykgiNTzst: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
    pJGidJSmpkqoZJU: THREE.MeshStandardMaterial;
    pueCqTeVMmaUmSr: THREE.MeshStandardMaterial;
    nxZSRGOrkZuiBOL: THREE.MeshStandardMaterial;
    RWIxOmVjlQCyowf_1: THREE.MeshStandardMaterial;
    WaTFoANPRxreBrE: THREE.MeshStandardMaterial;
    JbkUHwfUMhKPsVU: THREE.MeshStandardMaterial;
    Cam_Glass: THREE.MeshStandardMaterial;
    Flash: THREE.MeshStandardMaterial;
    Flash_0: THREE.MeshStandardMaterial;
    Antenna_Plastic: THREE.MeshStandardMaterial;
    Rearcase_hole: THREE.MeshStandardMaterial;
    Sensor: THREE.MeshStandardMaterial;
    SpeakerMic_0: THREE.MeshStandardMaterial;
    Flash_1: THREE.MeshStandardMaterial;
    Rearcase: THREE.MeshStandardMaterial;
    Pen_Body: THREE.MeshStandardMaterial;
    BackCamDeco: THREE.MeshStandardMaterial;
    Back_Cover_Glass: THREE.MeshStandardMaterial;
    Bezel: THREE.MeshStandardMaterial;
    Black_hole: THREE.MeshStandardMaterial;
    Cam_Bezel: THREE.MeshStandardMaterial;
    Cam_Body: THREE.MeshStandardMaterial;
    RWIxOmVjlQCyowf_2: THREE.MeshStandardMaterial;
    Wood_0: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    AAwwZzgtkuPlzHG: THREE.MeshStandardMaterial;
    lLHxDzeGesTXsDV: THREE.MeshStandardMaterial;
    jBmFawgSnuFgwvz: THREE.MeshStandardMaterial;
    inVgKrsjPCHlidG: THREE.MeshStandardMaterial;
    lqsMNfAMfMMYNWh: THREE.MeshStandardMaterial;
    SpeakerMic_1: THREE.MeshStandardMaterial;
    kiplkEfHPICMwOL: THREE.MeshStandardMaterial;
    Wood_1: THREE.MeshStandardMaterial;
    LDkudPLsuhAeDOm: THREE.MeshStandardMaterial;
    xhFoqVSMOeACiXV: THREE.MeshStandardMaterial;
    wYuvWRhcBAnXIkk: THREE.MeshStandardMaterial;
    ShHQJgcVqRHxvCB: THREE.MeshStandardMaterial;
    fLPLjcBAOBBZMBG: THREE.MeshStandardMaterial;
    zMLlCcSBPIDbYDP: THREE.MeshStandardMaterial;
    lrBjRRoUCQJnnrw: THREE.MeshStandardMaterial;
    HmbIobmriOJHOjV: THREE.MeshStandardMaterial;
    MEIyWDLxyHySdQS: THREE.MeshStandardMaterial;
    bHMusfkozOIvqtp: THREE.MeshStandardMaterial;
    FLgLVPAjfWzuEtb: THREE.MeshStandardMaterial;
    KYAZVdlNwZfXbEf: THREE.MeshStandardMaterial;
    BhzUwdkPybcVRaA: THREE.MeshStandardMaterial;
    bEezaHeEnrDoiaK: THREE.MeshStandardMaterial;
    QlBwJAiKCnKYdcl: THREE.MeshStandardMaterial;
    ['Glass.002']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.015']: THREE.MeshStandardMaterial;
    Wood_2: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
    emission: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
    alarm_sign: THREE.MeshStandardMaterial;
    Wood_3: THREE.MeshStandardMaterial;
    knob: THREE.MeshStandardMaterial;
    knob_2: THREE.MeshStandardMaterial;
    Rubber: THREE.MeshStandardMaterial;
    SILVER: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    Copper: THREE.MeshStandardMaterial;
    black_032half_032matte: THREE.MeshStandardMaterial;
    Grill: THREE.MeshStandardMaterial;
    Led_Cover: THREE.MeshStandardMaterial;
    Smooth_032Rubber: THREE.MeshStandardMaterial;
    White_032Reflector: THREE.MeshStandardMaterial;
    Wood_4: THREE.MeshStandardMaterial;
    Wood_5: THREE.MeshStandardMaterial;
    ['Metal_preto.001']: THREE.MeshStandardMaterial;
    Metal_cromado: THREE.MeshStandardMaterial;
    Metal_ouro: THREE.MeshStandardMaterial;
    Sheets: THREE.MeshStandardMaterial;
    Cover: THREE.MeshStandardMaterial;
    Binding: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export default function WorkSpaceModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/fixed/work-space.glb'
  ) as GLTFResult;

  const macScreen = useVideoTexture('/videos/minh_macbook_screen.mp4');

  const macScreenMaterial = new THREE.MeshBasicMaterial({ 
    map: macScreen,
    side: THREE.DoubleSide
  });

  macScreen.flipY = true;

  return (
    <group position={[0.02, -1.15, 0.25]}>
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.852}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            {/* Start Imac */}
            <group
              position={[-2.044, 95.487, 62.52]}
              rotation={[Math.PI, -Math.PI / 2, 0]}
              scale={59.173}>
              <mesh
                geometry={nodes.Object_8_txmOgsLZbdKJcEU_0.geometry}
                material={materials.txmOgsLZbdKJcEU}
              />
              <mesh
                geometry={nodes.Object_11_Metal001_0.geometry}
                material={materials['Metal.001']}
                position={[0.021, -0.216, 0]}
              />
              <mesh
                geometry={nodes.Object_13_Metal2001_0.geometry}
                material={materials['Metal2.001']}
                position={[0.02, -0.216, 0]}
              />
              <mesh
                geometry={nodes.Object_16_LightBlue001_0.geometry}
                material={materials['LightBlue.001']}
                position={[0.032, -0.284, -0.104]}
              />
              <mesh
                geometry={nodes.Object_16001_screen_0.geometry}
                material={materials.RWIxOmVjlQCyowf}
                position={[-0.048, -0.8, 0]}
              />
              <mesh
                geometry={nodes.Object_16002_screen_0.geometry}
                material={materials.RWIxOmVjlQCyowf}
                position={[-0.028, -0.694, 0]}
              />
              <mesh
                geometry={nodes.Object_18_txmOgsLZbdKJcEU_0.geometry}
                material={materials.txmOgsLZbdKJcEU}
                position={[0.025, -0.335, -0.021]}
              />
              <mesh
                geometry={nodes.Object_22001_White001_0.geometry}
                material={materials.Merged_materials}
                position={[0.016, -0.423, -0.177]}
              />
              <mesh
                geometry={nodes.Object_26_Chrome001_0.geometry}
                material={materials['Chrome.001']}
                position={[0.065, -0.076, 0]}
              />
              <mesh
                geometry={nodes.Object_28_CamBlack001_0.geometry}
                material={materials.Merged_materials}
                position={[-0.047, -0.8, 0]}
              />
              <mesh
                geometry={nodes.Object_30_Lens001_0.geometry}
                material={materials.Merged_materials}
                position={[-0.047, -0.8, 0]}
              />
              <mesh
                geometry={nodes.Object_32_Glass001_0.geometry}
                material={materials.Merged_materials}
                position={[-0.046, -0.8, 0]}
              />
              <mesh
                geometry={nodes.Object_34_Black002_0.geometry}
                material={materials['Black.002']}
                position={[0.066, -0.074, 0.364]}
              />
              <mesh
                geometry={nodes.Object_36_Yellow001_0.geometry}
                material={materials.Merged_materials}
                position={[0.067, -0.074, 0.364]}
              />
            </group>
            {/* End Imac */}
            {/* Start Chair */}
            <group
              position={[-2, 66, -32]}
              rotation={[-0.659, 1.556, 0.66]}
              scale={2.861}>
              <mesh
                geometry={nodes.Object_4_carbon_0.geometry}
                material={materials.carbon}
              />
              <mesh
                geometry={nodes.Object_5_carbon_0.geometry}
                material={materials.carbon}
              />
            </group>
            {/* End Chair */}
            {/* Start Samsung */}
            {/* <group
              position={[33.339, 85.826, 34.832]}
              rotation={[Math.PI / 2, 0, Math.PI]}
              scale={2.685}>
              <group
                position={[2.479, -0.039, -0.001]}
                rotation={[0, 0, -0.273]}>
                <mesh
                  geometry={nodes.Object_28001_Rearcase_0.geometry}
                  material={materials.Rearcase}
                />
                <mesh
                  geometry={nodes.Object_17_Pen_Body_0.geometry}
                  material={materials.Pen_Body}
                  position={[0, -2.73, -0.002]}
                />
                <mesh
                  geometry={nodes.Object_18001_Pen_Button_0.geometry}
                  material={materials.Merged_materials}
                  position={[0, -2.014, -0.061]}
                />
                <mesh
                  geometry={nodes.Object_19_Pen_Top_0.geometry}
                  material={materials.Merged_materials}
                  position={[0, -0.113, 0.001]}
                />
              </group>
              <mesh
                geometry={nodes.Object_12_samsung_display_0.geometry}
                material={materials.RWIxOmVjlQCyowf_2}
              />
              <mesh
                geometry={nodes.Object_10_Cam_Glass_0.geometry}
                material={materials.Cam_Glass}
                position={[0.552, -4.461, 0.168]}
              />
              <mesh
                geometry={nodes.Object_11001_Cam_lens_0.geometry}
                material={materials.Flash}
                position={[0.565, -4.566, 0.104]}
              />
              <mesh
                geometry={nodes.Object_13001_Flash_0.geometry}
                material={materials.Flash_0}
                position={[0.277, -4.599, 0.138]}
              />
              <mesh
                geometry={nodes.Object_14_Flash_Glass_0.geometry}
                material={materials.Merged_materials}
                position={[0.277, -4.599, 0.143]}
              />
              <mesh
                geometry={nodes.Object_15_Gray_0.geometry}
                material={materials.Merged_materials}
                position={[0.277, -4.814, 0.163]}
              />
              <mesh
                geometry={nodes.Object_2_Antenna_Plastic_0.geometry}
                material={materials.Antenna_Plastic}
                position={[-0.05, -1.7, 0]}
              />
              <mesh
                geometry={nodes.Object_20_Rearcase_hole_0.geometry}
                material={materials.Rearcase_hole}
                position={[-0.562, -0.319, -0.001]}
              />
              <mesh
                geometry={nodes.Object_21_SAMSUNG_LOGO_0.geometry}
                material={materials.Merged_materials}
                position={[0.009, -1.024, 0.145]}
              />
              <mesh
                geometry={nodes.Object_22_Sensor_0.geometry}
                material={materials.Sensor}
                position={[0.277, -4.912, 0.164]}
              />
              <mesh
                geometry={nodes.Object_23_SpeakerMic_0.geometry}
                material={materials.SpeakerMic_0}
                position={[-0.415, -0.522, 0]}
              />
              <mesh
                geometry={nodes.Object_24_Usb_1_0.geometry}
                material={materials.Sensor}
                position={[0, -0.143, 0]}
              />
              <mesh
                geometry={nodes.Object_25_Usb_2_0.geometry}
                material={materials.Merged_materials}
                position={[0, -0.118, 0]}
              />
              <mesh
                geometry={nodes.Object_26001_Zoom_Cam_0.geometry}
                material={materials.Flash_1}
                position={[0.776, -3.776, 0.091]}
              />
              <mesh
                geometry={nodes.Object_27_Rearcase_0.geometry}
                material={materials.Rearcase}
                position={[0.05, -1.949, 0]}
              />
              <mesh
                geometry={nodes.Object_29_material_0.geometry}
                material={materials.Merged_materials}
                position={[0.277, -4.946, 0.163]}
              />
              <mesh
                geometry={nodes.Object_3_BackCamDeco_0.geometry}
                material={materials.BackCamDeco}
                position={[0.645, -4.551, 0.153]}
              />
              <mesh
                geometry={nodes.Object_4001_BackCover_Glass_hole_0.geometry}
                material={materials.Sensor}
                position={[0.559, -4.443, 0.139]}
              />
              <mesh
                geometry={nodes.Object_5001_Back_Cover_Glass_0.geometry}
                material={materials.Back_Cover_Glass}
                position={[0.077, -2.906, 0.127]}
              />
              <mesh
                geometry={nodes.Object_6_Bezel_0.geometry}
                material={materials.Bezel}
                position={[0, -3.332, -0.127]}
              />
              <mesh
                geometry={nodes.Object_7_Black_hole_0.geometry}
                material={materials.Black_hole}
                position={[0.389, -3.125, 0.089]}
              />
              <mesh
                geometry={nodes.Object_8001_Cam_Bezel_0.geometry}
                material={materials.Cam_Bezel}
                position={[0.576, -4.433, 0.185]}
              />
              <mesh
                geometry={nodes.Object_9_Cam_Body_0.geometry}
                material={materials.Cam_Body}
                position={[0.591, -4.405, 0.112]}
              />
            </group> */}
            {/* End Samsung */}
            <group
              position={[41.103, 85.916, 42.108]}
              rotation={[Math.PI / 2, 0, Math.PI]}
              scale={0.029}>
              <group rotation={[Math.PI / 2, 0, 0]}>
                <group scale={13.669}>
                  <mesh
                    geometry={nodes.defaultMaterial001_Material001_0.geometry}
                    material={materials.Wood_0}
                  />
                  <mesh
                    geometry={nodes.defaultMaterial002_Material001_0.geometry}
                    material={materials.Wood_0}
                  />
                  <mesh
                    geometry={nodes.defaultMaterial003_Material002_0.geometry}
                    material={materials['Material.002']}
                  />
                </group>
              </group>
            </group>
            <group
              position={[41.368, 86.243, 42.189]}
              rotation={[0, 0, Math.PI]}
              scale={[0.497, 0.175, 0.497]}>
              <mesh
                geometry={nodes.Apple_0_Material_0.geometry}
                material={materials.Material}
              />
              <mesh
                geometry={nodes.Apple_0_Material002_0.geometry}
                material={materials['Material.002']}
              />
            </group>
            {/* Start Magic Keyboard */}
            <group
              position={[1, 85.953, 36]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.138}>
              <mesh
                geometry={nodes.RMOxPfNmwvXDNGs_txmOgsLZbdKJcEU_0.geometry}
                material={materials.txmOgsLZbdKJcEU}
              />
              <mesh
                geometry={nodes.AJbdxpwuEnTzrzs_AAwwZzgtkuPlzHG_0.geometry}
                material={materials.AAwwZzgtkuPlzHG}
                position={[0.175, -0.476, -0.144]}
              />
              <mesh
                geometry={nodes.AMHLoKClaWHHFTd_txmOgsLZbdKJcEU_0.geometry}
                material={materials.txmOgsLZbdKJcEU}
                position={[19.8, 5.176, -0.106]}
              />
              <mesh
                geometry={nodes.DDRlrgtqbHRuMFK_lLHxDzeGesTXsDV_0.geometry}
                material={materials.lLHxDzeGesTXsDV}
                position={[5.983, 4.111, 0.355]}
              />
              <mesh
                geometry={nodes.dJHERinFsWDVoRO_jBmFawgSnuFgwvz_0.geometry}
                material={materials.jBmFawgSnuFgwvz}
                position={[27.087, -0.48, 0.929]}
              />
              <mesh
                geometry={nodes.DyNEUHcqFmykLnq_inVgKrsjPCHlidG_0.geometry}
                material={materials.inVgKrsjPCHlidG}
                position={[-16.905, 5.244, -0.103]}
              />
              <mesh
                geometry={nodes.epNEVLwjxulvcVT_lqsMNfAMfMMYNWh_0.geometry}
                material={materials.lqsMNfAMfMMYNWh}
                position={[27.086, 3.141, -0.298]}
              />
              <mesh
                geometry={nodes.EvwofeNdSOiKwJA_ZxCcWNVXIHaKOMZ_0.geometry}
                material={materials.SpeakerMic_1}
                position={[26.964, 0.826, -0.512]}
              />
              <mesh
                geometry={nodes.fdelRQvrAPluxYI_DlUleWLCfHhnvHH_0.geometry}
                material={materials.Merged_materials}
                position={[19.918, 5.185, -0.106]}
              />
              <mesh
                geometry={nodes.fiEriZEEzWBKpIW_kiplkEfHPICMwOL_0.geometry}
                material={materials.kiplkEfHPICMwOL}
                position={[0.088, -0.387, -0.603]}
              />
              <mesh
                geometry={nodes.FPkLYEUKWIzIvRB_mnvREVAVeWlYOOT_0.geometry}
                material={materials.Wood_1}
                position={[19.921, 5.254, -0.102]}
              />
              <mesh
                geometry={nodes.gCWqWSEWWHMcDGU_LDkudPLsuhAeDOm_0.geometry}
                material={materials.LDkudPLsuhAeDOm}
                position={[27.107, -3.417, 1.149]}
              />
              <mesh
                geometry={nodes.gstnwkkYxUMfexU_xhFoqVSMOeACiXV_0.geometry}
                material={materials.xhFoqVSMOeACiXV}
                position={[0.051, -0.064, 0.124]}
              />
              <mesh
                geometry={nodes.ibtGhYAKvcwGziZ_rrvhCJMaYTHrDoz_0.geometry}
                material={materials.Wood_1}
                position={[26.228, 3.258, -0.622]}
              />
              <mesh
                geometry={nodes.idZbmiqfxcsskPw_wYuvWRhcBAnXIkk_0.geometry}
                material={materials.wYuvWRhcBAnXIkk}
                position={[-1.225, 0.009, 0.155]}
              />
              <mesh
                geometry={nodes.jANFYvUCGDdkwwM_ShHQJgcVqRHxvCB_0.geometry}
                material={materials.ShHQJgcVqRHxvCB}
                position={[0.165, 4.861, -0.172]}
              />
              <mesh
                geometry={nodes.JYlWWVpXsttJXNT_fLPLjcBAOBBZMBG_0.geometry}
                material={materials.fLPLjcBAOBBZMBG}
                position={[5.983, 4.111, 0.356]}
              />
              <mesh
                geometry={nodes.kgVGkcNjSqcogpi_zMLlCcSBPIDbYDP_0.geometry}
                material={materials.zMLlCcSBPIDbYDP}
                position={[0.186, -0.47, -0.659]}
              />
              <mesh
                geometry={nodes.KvIMyWFPpFISdov_lrBjRRoUCQJnnrw_0.geometry}
                material={materials.lrBjRRoUCQJnnrw}
                position={[27.084, -3.966, -0.278]}
              />
              <mesh
                geometry={nodes.KwHYbQNqIDhjHSe_txmOgsLZbdKJcEU_0.geometry}
                material={materials.txmOgsLZbdKJcEU}
                position={[27.072, -0.413, -0.393]}
              />
              <mesh
                geometry={nodes.MEVcNNvcPYMgxhw_axGqhJIfzrbRmtI_0.geometry}
                material={materials.Merged_materials}
                position={[19.619, 5.125, -0.108]}
              />
              <mesh
                geometry={nodes.mJlqEXxPCKLwQZq_HmbIobmriOJHOjV_0.geometry}
                material={materials.HmbIobmriOJHOjV}
                position={[27.018, -0.311, -0.623]}
              />
              <mesh
                geometry={nodes.NoxSUxuQtcYfBlX_MEIyWDLxyHySdQS_0.geometry}
                material={materials.MEIyWDLxyHySdQS}
                position={[7.86, 1.677, -0.35]}
              />
              <mesh
                geometry={nodes.NZWwoBiiqXPyUvr_JUvPVJgNgUOAMPH_0.geometry}
                material={materials.RWIxOmVjlQCyowf_0}
                position={[2.838, 0.158, -0.422]}
              />
              <mesh
                geometry={nodes.ohJAMQPFJETFsDW_NebQvzRLlLTGfUN_0.geometry}
                material={materials.Merged_materials}
                position={[-20.09, -0.998, 0.112]}
              />
              <mesh
                geometry={nodes.PGROoHXqRGLyzpv_jBmFawgSnuFgwvz_0.geometry}
                material={materials.jBmFawgSnuFgwvz}
                position={[27.086, -0.398, 0.393]}
              />
              <mesh
                geometry={nodes.pHQfWFRRACikJLz_JUvPVJgNgUOAMPH_0.geometry}
                material={materials.RWIxOmVjlQCyowf_0}
                position={[5.983, 4.115, 0.278]}
              />
              <mesh
                geometry={nodes.PuPREzUbjRnwByi_DOGSvSvaIOKOGEB_0.geometry}
                material={materials.Merged_materials}
                position={[26.228, 3.263, -0.571]}
              />
              <mesh
                geometry={nodes.QxirwGJHRdjmSQM_sTZzuJicxcBhqMT_0.geometry}
                material={materials.Merged_materials}
                position={[26.23, 3.082, -0.52]}
              />
              <mesh
                geometry={nodes.rrgnrcJtagJiaPm_JUvPVJgNgUOAMPH_0.geometry}
                material={materials.RWIxOmVjlQCyowf_0}
                position={[27.046, -0.351, 0.291]}
              />
              <mesh
                geometry={nodes.sbMQfpLUHxjxYbY_bHMusfkozOIvqtp_0.geometry}
                material={materials.bHMusfkozOIvqtp}
                position={[27.011, 1.394, -0.273]}
              />
              <mesh
                geometry={nodes.SDBahcjiXkZtYxZ_FLgLVPAjfWzuEtb_0.geometry}
                material={materials.FLgLVPAjfWzuEtb}
                position={[0.165, 4.755, -0.21]}
              />
              <mesh
                geometry={nodes.SgUfbhhareNQkuj_xhFoqVSMOeACiXV_0.geometry}
                material={materials.xhFoqVSMOeACiXV}
                position={[5.983, 4.111, 0.344]}
              />
              <mesh
                geometry={nodes.sqpzxMMcSNEzeaN_KYAZVdlNwZfXbEf_0.geometry}
                material={materials.KYAZVdlNwZfXbEf}
                position={[27.086, -4.037, -0.32]}
              />
              <mesh
                geometry={nodes.UcDFxvKUvTmdLHf_txmOgsLZbdKJcEU_0.geometry}
                material={materials.txmOgsLZbdKJcEU}
                position={[0.165, 5.17, -0.106]}
              />
              <mesh
                geometry={nodes.vVWnLQQWauJmoea_BhzUwdkPybcVRaA_0.geometry}
                material={materials.BhzUwdkPybcVRaA}
                position={[27.127, 3.134, -0.297]}
              />
              <mesh
                geometry={nodes.WggVFGrkJUBSkuH_txmOgsLZbdKJcEU_0.geometry}
                material={materials.txmOgsLZbdKJcEU}
                position={[2.2, 0.603, -0.325]}
              />
              <mesh
                geometry={nodes.WHTbdsLSupTMovb_ZxCcWNVXIHaKOMZ_0.geometry}
                material={materials.SpeakerMic_1}
                position={[27.086, -3.967, -0.278]}
              />
              <mesh
                geometry={nodes.xVttQMiYmYuArAD_kiplkEfHPICMwOL_0.geometry}
                material={materials.kiplkEfHPICMwOL}
                position={[0.021, -0.056, -0.609]}
              />
              <mesh
                geometry={nodes.YAznSNOjLfkryuQ_bEezaHeEnrDoiaK_0.geometry}
                material={materials.bEezaHeEnrDoiaK}
                position={[27.086, -0.448, -0.568]}
              />
              <mesh
                geometry={nodes.ysyLqNtrPcvbRdQ_QlBwJAiKCnKYdcl_0.geometry}
                material={materials.QlBwJAiKCnKYdcl}
                position={[27.086, -0.4, 0.341]}
              />
              <mesh
                geometry={nodes.zmxolQOwzgtuHGo_ynLkpcwlGVMwvHR_0.geometry}
                material={materials.FLgLVPAjfWzuEtb}
                position={[27.086, -3.976, -0.246]}
              />
              <mesh
                geometry={nodes.ZrGEEtRvTICtxtV_UvbMHfZlJbAYJww_0.geometry}
                material={materials.KYAZVdlNwZfXbEf}
                position={[0.165, 4.772, -0.125]}
              />
            </group>
            {/* End Magic Keyboard */}
            <group
              position={[-54.794, 86.285, 77.61]}
              rotation={[-Math.PI / 2, 0, 0.013]}
              scale={[129.748, 129.748, 180.575]}>
              <group
                position={[-0.026, 0.182, 0.232]}
                rotation={[0.093, 0.095, 1.734]}
                scale={[1.053, 1.056, 0.764]}>
                <group position={[0, 0.001, -0.006]}>
                  <mesh
                    geometry={nodes.Cylinder043_Material003_0.geometry}
                    material={materials['Material.003']}
                  />
                  <mesh
                    geometry={nodes.Cylinder044_Material003_0.geometry}
                    material={materials['Material.003']}
                    position={[0, 0, -0.089]}
                    scale={[0.049, 0.048, 0.03]}
                  />
                </group>
                <mesh
                  geometry={nodes.Cylinder056__0.geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  geometry={nodes.Cylinder055_Glass002_0.geometry}
                  material={materials['Glass.002']}
                  position={[0, 0, -0.054]}
                />
              </group>
              <mesh
                geometry={nodes.Desk_lamp_Wood_0.geometry}
                material={materials.Wood_2}
              />
              <mesh
                geometry={nodes.Plane002__0.geometry}
                material={materials.Merged_materials}
                position={[-0.005, 0, 0.139]}
                rotation={[0, 0, 1.733]}
                scale={[0.387, 0.387, 0.278]}
              />
              <mesh
                geometry={nodes.Cylinder047_Material015_0.geometry}
                material={materials['Material.015']}
                position={[-0.023, 0.175, 0.282]}
                rotation={[0.093, 0.095, 1.734]}
                scale={[1.053, 1.056, 0.764]}
              />
              <mesh
                geometry={nodes.Cylinder042_Material003_0.geometry}
                material={materials['Material.003']}
                position={[-0.012, 0.125, 0.264]}
                rotation={[-Math.PI / 2, 1.409, -Math.PI / 2]}
                scale={[0.759, 1.056, 1.056]}
              />
              <mesh
                geometry={nodes.Cube073_Wood_0.geometry}
                material={materials.Wood_2}
                position={[-0.004, 0.029, 0.235]}
                rotation={[-1.103, -0.291, 1.738]}
                scale={[0.817, 1.056, 1.011]}
              />
              <mesh
                geometry={nodes.Cube072_Wood_0.geometry}
                material={materials.Wood_2}
                position={[0.006, -0.03, 0.114]}
                rotation={[0.396, 0.207, 1.753]}
                scale={[1.014, 1.056, 0.814]}
              />
              <mesh
                geometry={nodes.Cube071_Wood_0.geometry}
                material={materials.Wood_2}
                position={[0.001, 0.003, 0.041]}
                rotation={[0, 0, 1.733]}
                scale={[1.056, 1.056, 0.759]}
              />
            </group>
            <group
              position={[29.157, 84.288, 75.614]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={5.356}>
              <group
                position={[0, 0.432, 1.546]}
                rotation={[-Math.PI, 0, 0]}
                scale={0.197}>
                <mesh
                  geometry={nodes.Object_4002_emission_0.geometry}
                  material={materials.emission}
                />
                <mesh
                  geometry={nodes.Object_5002_Material005_0.geometry}
                  material={materials['Material.005']}
                />
              </group>
              <mesh
                geometry={nodes.Object_12001_glass_0.geometry}
                material={materials.glass}
                position={[0, 0.08, 0.978]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Object_16003_Material010_0.geometry}
                material={materials.Wood_3}
                position={[0, -0.182, 0.978]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <group
                position={[-1.529, 0.432, 0.978]}
                rotation={[0, Math.PI / 2, 0]}
                scale={0.2}>
                <mesh
                  geometry={nodes.Object_18002_knob_0.geometry}
                  material={materials.knob}
                />
                <mesh
                  geometry={nodes.Object_19001_knob_2_0.geometry}
                  material={materials.knob_2}
                />
              </group>
              <mesh
                geometry={nodes.Object_10001_Material004_0.geometry}
                material={materials['Material.004']}
              />
              <mesh
                geometry={nodes.Object_9001_Material005_0.geometry}
                material={materials['Material.005']}
              />
              <mesh
                geometry={nodes.Object_14001_Material005_0.geometry}
                material={materials['Material.005']}
              />
              <mesh
                geometry={nodes.Object_7001_alarm_sign_0.geometry}
                material={materials.alarm_sign}
              />
            </group>
            <group
              position={[-63.453, 85.127, 43.9]}
              rotation={[-3.135, 0, 0]}
              scale={12.92}>
              <mesh
                geometry={nodes.Object_10002_Rubber_0.geometry}
                material={materials.Rubber}
              />
              <mesh
                geometry={nodes.Object_11002_Rubber_0.geometry}
                material={materials.Rubber}
              />
              <mesh
                geometry={nodes.Object_12002_Rubber_0.geometry}
                material={materials.Rubber}
              />
              <mesh
                geometry={nodes.Object_13002_Rubber_0.geometry}
                material={materials.Rubber}
              />
              <mesh
                geometry={nodes.Object_14002_txmOgsLZbdKJcEU_0.geometry}
                material={materials.txmOgsLZbdKJcEU}
              />
              <mesh
                geometry={nodes.Object_15001_Rubber_0.geometry}
                material={materials.Rubber}
              />
              <mesh
                geometry={nodes.Object_16004_Rubber_0.geometry}
                material={materials.Rubber}
              />
              <mesh
                geometry={nodes.Object_17001_Rubber_0.geometry}
                material={materials.Rubber}
              />
              <mesh
                geometry={nodes.Object_18003_SILVER_0.geometry}
                material={materials.SILVER}
              />
              <mesh
                geometry={nodes.Object_19002_Material007_0.geometry}
                material={materials['Material.007']}
              />
              <mesh
                geometry={nodes.Object_2001_Copper_0.geometry}
                material={materials.Copper}
              />
              <mesh
                geometry={nodes.Object_20001_txmOgsLZbdKJcEU_0.geometry}
                material={materials.txmOgsLZbdKJcEU}
              />
              <mesh
                geometry={nodes.Object_21001_black_032half_032matte_0.geometry}
                material={materials.black_032half_032matte}
              />
              <mesh
                geometry={nodes.Object_22002_txmOgsLZbdKJcEU_0.geometry}
                material={materials.txmOgsLZbdKJcEU}
              />
              <mesh
                geometry={nodes.Object_3001_Grill_0.geometry}
                material={materials.Grill}
              />
              <mesh
                geometry={nodes.Object_4003_Led_032Emitter_0.geometry}
                material={materials.Merged_materials}
              />
              <mesh
                geometry={nodes.Object_5003_Led_Cover_0.geometry}
                material={materials.Led_Cover}
              />
              <mesh
                geometry={nodes.Object_6001_Smooth_032Rubber_0.geometry}
                material={materials.Smooth_032Rubber}
              />
              <mesh
                geometry={nodes.Object_7002_White_032Reflector_0.geometry}
                material={materials.White_032Reflector}
              />
              <mesh
                geometry={nodes.Object_8002_label_0.geometry}
                material={materials.Wood_4}
              />
              <mesh
                geometry={nodes.Object_9002_Rubber_0.geometry}
                material={materials.Rubber}
              />
            </group>
            <group
              position={[64.008, 85.426, 38.008]}
              rotation={[-Math.PI / 2, 0, -3.018]}
              scale={100}>
              <group position={[0, 0.003, 0.002]}>
                <mesh
                  geometry={nodes.Plane060_paper001_0.geometry}
                  material={materials.Wood_2}
                />
                <mesh
                  geometry={nodes.Plane060_paper001_0_1.geometry}
                  material={materials.Wood_2}
                />
                <mesh
                  geometry={nodes.Plane060_paper001_0_2.geometry}
                  material={materials.Wood_2}
                />
                <mesh
                  geometry={nodes.Plane060_paper001_0_3.geometry}
                  material={materials.Wood_2}
                />
                <mesh
                  geometry={nodes.Plane060_paper001_0_4.geometry}
                  material={materials.Wood_2}
                />
                <mesh
                  geometry={nodes.Plane060_paper001_0_5.geometry}
                  material={materials.Wood_2}
                />
                <mesh
                  geometry={nodes.Plane060_couro_2k_0.geometry}
                  material={materials.Wood_2}
                />
                <mesh
                  geometry={nodes.Plane060_Material009_0.geometry}
                  material={materials.Wood_2}
                />
              </group>
              <group position={[0.006, -0.073, 0.019]}>
                <mesh
                  geometry={nodes.Cylinder001_Metal_preto001_0.geometry}
                  material={materials['Metal_preto.001']}
                />
                <mesh
                  geometry={nodes.Cylinder001_Metal_cromado_0.geometry}
                  material={materials.Metal_cromado}
                />
              </group>
              <mesh
                geometry={nodes.Circle_Metal_ouro_0.geometry}
                material={materials.Metal_ouro}
                position={[-0.087, 0.096, 0.001]}
              />
            </group>
            <group
              position={[97.162, 86.738, 64.741]}
              rotation={[-Math.PI / 2, 0, -2.98]}
              scale={4.98}>
              <group rotation={[0.03, 0, 0]}>
                <mesh
                  geometry={nodes.Object_4004_Sheets_0.geometry}
                  material={materials.Sheets}
                />
                <mesh
                  geometry={nodes.Object_4004_Sheets_0_1.geometry}
                  material={materials.Sheets}
                />
                <mesh
                  geometry={nodes.Object_4004_Sheets_0_2.geometry}
                  material={materials.Sheets}
                />
              </group>
              <mesh
                geometry={nodes.Object_5004_Sheets_0.geometry}
                material={materials.Sheets}
                rotation={[0.036, 0, 0]}
              />
              <mesh
                geometry={nodes.Object_6005_Cover_0.geometry}
                material={materials.Cover}
                rotation={[0.03, 0, 0]}
              />
              <mesh
                geometry={nodes.Object_7004_Binding_0.geometry}
                material={materials.Binding}
              />
            </group>
            <mesh
              geometry={nodes.Modern_Office_Desk_Marble_0.geometry}
              material={materials.Marble}
              position={[-3.62, -0.035, 23.693]}
              rotation={[Math.PI, Math.PI / 2, 0]}
              scale={10.67}
            />
            <mesh
              geometry={nodes.aiHhzEmqAnKWvuZ_EFVjrvWSJmAgjPd_0.geometry}
              material={materials.EFVjrvWSJmAgjPd}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.bGQMFmxTXZZEOSB_sIvkPEZgWXyskPl_0.geometry}
              material={materials.sIvkPEZgWXyskPl}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.BhmwvFLjAMopdsz_UhciuwjbkbbeuzB_0.geometry}
              material={materials.UhciuwjbkbbeuzB}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.COalyZNmKBMRDJA_RWIxOmVjlQCyowf_0.geometry}
              material={materials.RWIxOmVjlQCyowf_0}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.cTxlpXifIUtmOwe_CUqnbzGvHvsjfjx_0.geometry}
              material={materials.RWIxOmVjlQCyowf_0}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.dIGFCvApVXVovwW_UFhCTmjKLQhiPGC_0.geometry}
              material={materials.UFhCTmjKLQhiPGC}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.DucfrfCAqHqPEBB_DEAWTVXLuSZtcDP_0.geometry}
              material={materials.HRWfsqTNPFmjalx}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.eaMMaIHSUtZTmwM_rXOHcxkhnKbZRNb_0.geometry}
              material={materials.rXOHcxkhnKbZRNb}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.eJrZgbUbLcjUmXb_HRWfsqTNPFmjalx_0.geometry}
              material={materials.HRWfsqTNPFmjalx}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.EjxsCCuCosYwuek_IvcPCDoDmyBTWLH_0.geometry}
              material={materials.IvcPCDoDmyBTWLH}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.elzKjZVZogRbidI_uQtVjGIzYkvkoNE_0.geometry}
              material={materials.SpeakerMic}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.gMjIpJkwdihsuve_QWnVWluKdJslXlp_0.geometry}
              material={materials.QWnVWluKdJslXlp}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.grgDQRSnIrRfYHl_qJYXGHykgiNTzst_0.geometry}
              material={materials.qJYXGHykgiNTzst}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.hbRQuyafLOAJHbc_IMKGQaLyUgfVxBg_0.geometry}
              material={materials.Merged_materials}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.hmCcMVIPuALtvnB_NizfUyGpiAoDFWH_0.geometry}
              material={materials.HRWfsqTNPFmjalx}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.IvQyRpNNnwrbsxL_sIvkPEZgWXyskPl_0.geometry}
              material={materials.sIvkPEZgWXyskPl}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.jdDNrasBlJHUmOI_RWIxOmVjlQCyowf_0.geometry}
              material={materials.RWIxOmVjlQCyowf_0}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.jfcwgJrUYqWmTbS_kMVeqkDlEeNLAmH_0.geometry}
              material={materials.RWIxOmVjlQCyowf_0}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.LBPtZdGyIpXPukr_yifgXaDcdXXvJAt_0.geometry}
              material={materials.Merged_materials}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.LLOlBTHSUCLvvWd_DEAWTVXLuSZtcDP_0.geometry}
              material={materials.HRWfsqTNPFmjalx}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.MgIBLXqrHqrffJA_UhciuwjbkbbeuzB_0.geometry}
              material={materials.UhciuwjbkbbeuzB}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.MNJNItsqFHPCYBO_RWIxOmVjlQCyowf_0.geometry}
              material={materials.RWIxOmVjlQCyowf_0}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.ogZjMUJrEEmipKZ_nsOjGvnekvGXrhm_0.geometry}
              material={materials.Wood}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.pDHQtpoBgcNkYgT_pJGidJSmpkqoZJU_0.geometry}
              material={materials.pJGidJSmpkqoZJU}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.PwgdzFHtyijxfkM_pueCqTeVMmaUmSr_0.geometry}
              material={materials.pueCqTeVMmaUmSr}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.pwunQleuznjoKDo_zSrAlRDhvfAhSPV_0.geometry}
              material={materials.Merged_materials}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.PZkUDTueaTlRUIB_RWIxOmVjlQCyowf_0.geometry}
              material={materials.RWIxOmVjlQCyowf_0}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.QQjtoFlaLxDYFcf_nxZSRGOrkZuiBOL_0.geometry}
              material={materials.nxZSRGOrkZuiBOL}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.QWynJfbYSasNZHl_rXOHcxkhnKbZRNb_0.geometry}
              material={materials.rXOHcxkhnKbZRNb}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.rZZGdJgeDlvDaPX_UFhCTmjKLQhiPGC_0.geometry}
              material={materials.UFhCTmjKLQhiPGC}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.SbeMRorWoNyXlAe_ZchRNZkxDgmgJXH_0.geometry}
              material={materials.Merged_materials}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            {/* Start Macbook Screen */}
            <mesh
              geometry={nodes.SDFncRVROIaGmdP_Material006_0.geometry}
              material={macScreenMaterial}
              position={[42.295, 85.801, 79]}
              rotation={[-1.12, 0, 0]}
              scale={1.207}
            />
            {/* End Macbook Screen */}
            <mesh
              geometry={nodes.SDXaYLHOunwCLHZ_CUqnbzGvHvsjfjx_0.geometry}
              material={materials.RWIxOmVjlQCyowf_0}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.ssmfkcRvklZSIzZ_EFVjrvWSJmAgjPd_0.geometry}
              material={materials.EFVjrvWSJmAgjPd}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.tIqFBnXlPHHchZM_CUqnbzGvHvsjfjx_0.geometry}
              material={materials.RWIxOmVjlQCyowf_0}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.UOKfQrXTIiZEYIa_pueCqTeVMmaUmSr_0.geometry}
              material={materials.pueCqTeVMmaUmSr}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.VeBGZTrfnhHdOwL_CUqnbzGvHvsjfjx_0.geometry}
              material={materials.RWIxOmVjlQCyowf_0}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.veExVWBHjiIlgtN_WaTFoANPRxreBrE_0.geometry}
              material={materials.WaTFoANPRxreBrE}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.vERhpGKnTDAqPYM_OqztnpgkHPpVRLf_0.geometry}
              material={materials.Merged_materials}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.VkZCcwdEWjLPPEB_RWIxOmVjlQCyowf_0.geometry}
              material={materials.RWIxOmVjlQCyowf_0}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.vUnJNCoGwAVQHLJ_EFVjrvWSJmAgjPd_0.geometry}
              material={materials.EFVjrvWSJmAgjPd}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.vurcCjJgfXlGxGa_sIvkPEZgWXyskPl_0.geometry}
              material={materials.sIvkPEZgWXyskPl}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.WZNlAtpdtvoXdBP_UhciuwjbkbbeuzB_0.geometry}
              material={materials.UhciuwjbkbbeuzB}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.XqkMoScNZNSWfSO_pueCqTeVMmaUmSr_0.geometry}
              material={materials.pueCqTeVMmaUmSr}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.yyGZPAZQuGPMcxX_sIvkPEZgWXyskPl_0.geometry}
              material={materials.sIvkPEZgWXyskPl}
              position={[60.303, 86.215, 65.298]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.zXWNaEcOhoAIySc_JbkUHwfUMhKPsVU_0.geometry}
              material={materials.JbkUHwfUMhKPsVU}
              position={[78.28, 85.801, 78.067]}
              rotation={[-1.809, 0, -Math.PI]}
              scale={1.207}
            />
            <mesh
              geometry={nodes.Object_15002_sofa_1M_0.geometry}
              material={materials.Wood_5}
              position={[88.842, 113.829, 76.481]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={413.502}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/fixed/work-space.glb');
